CREATE TABLE IF NOT EXISTS parks (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    address CHAR(100) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS cars (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    park_id INT UNSIGNED DEFAULT NULL,
    model VARCHAR(100) NOT NULL,
    price FLOAT NOT NULL,
    FOREIGN KEY (park_id) REFERENCES parks (id)
) ENGINE = InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS drivers (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    car_id INT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(100),
    FOREIGN KEY (car_id) REFERENCES cars (id)
) ENGINE = InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS orders (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    driver_id INT UNSIGNED NOT NULL,
    customer_id INT UNSIGNED NOT NULL,
    start TEXT NOT NULL,
    finish TEXT NOT NULL,
    total FLOAT NOT NULL,
    FOREIGN KEY (driver_id) REFERENCES drivers (id),
    FOREIGN KEY (customer_id) REFERENCES customers (id)
) ENGINE = InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS customers (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(100)
) ENGINE = InnoDB CHARACTER SET utf8;